%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\dazef\OneDrive\Documenti\Dottorato\FW no drop\Clique problems\DIMACS_subset_ascii\brock200_2.clq
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2020/06/30 16:44:50

%% Initialize variables.
function Gedges = graphcreator2(s)
    filename = strcat('instances\', s, '.clq.txt');
    delimiter = ' ';   

    %% Format for each line of text:
    %   column2: double (%f)
    %	column3: double (%f)
    % For more information, see the TEXTSCAN documentation.
    formatSpec = '%*s%f%f%*s%*s%*s%*s%*s%*s%*s%*s%[^\n\r]';

    %% Open the text file.
    fileID1 = fopen(filename, 'r');
    s = textscan(fileID1, '%s', 'delimiter', '\n');   
    fclose(fileID1);
    idx1 = find(~cellfun(@isempty,regexp(s{1},'^e \d+ \d+')), 1, 'first');
    fileID = fopen(filename,'r');

    %% Read columns of data according to the format.
    % This call is based on the structure of the file used to generate this
    % code. If an error occurs for a different file, try regenerating the code
    % from the Import Tool.s = textscan(fid, '%s', 'delimiter', '\n');
    % search for your Region:

    dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines' ,idx1 - 1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    
    %% Close the text file.
    fclose(fileID);

    %% Post processing for unimportable data.
    % No unimportable data rules were applied during the import, so no post
    % processing code is included. To generate code which works for
    % unimportable data, select unimportable cells in a file and regenerate the
    % script.

    %% Create output variable
    tabgraph = table(dataArray{1:end-1}, 'VariableNames', {'Graph','Size200'});

    %% Clear temporary variables
    clearvars filename delimiter startRow formatSpec fileID dataArray ans;
    Gedges = table2array(tabgraph);
end